language: node_js
node_js:
- stable
cache:
  directories:
  - client/node_modules
  - server/node_modules
script:
- bash scripts/travis_test.sh
- bash scripts/travis_build.sh
true:
  branch: master
os:
- osx
deploy:
  provider: heroku
  api_key:
    secure: dRm4wiKn/RvBXC8OIjE5zryGGlJzcEAtBv7/UDvVDRUptB4E4V3zrOm1yyclJGojboFlVHnU/A5hVW36zINWLTCbfcj4wRdjNnvDGuxKRUwrtMzXpwjoD3ckOJ0aL6PfCwGG6zuFzoFxwe950Ky34FKPy8Re8HNlpuzel556Ulbo0kKQgmdJsYLfTke183sgNr/0v0CTwlGhFkBQ8BNXq9Xt9lHsW2vkzTU7HWHn4S6aHDBJm6/8SBQ/4aQdMOKPeCxQVP3m780sSXvSMzzhMO8qQL1f2SZSW6lTIE8bkhFUNQ09e3aqWnpAtrLzHcbT9vgP2+qWZ6ssoW7EkTiw5i+atloFMOrbTzYKX8lfArvnwIMOHAjJBOW96kaC6ZesJtpr2SFQpe+azZ2rnM0rlmhUI2UZawOUTIb0Ek7WXFSPM2Tn/jhgWX17CtPHZnxSuGPkX9by71e/7nReYiTGspl6uFrTZhSvyVohubyYN9SASbKXeM3vOzNubkvxQDcLzPSPk4W+DQsIr2L/KclGG69IuaHKFghYUVIy77VVrhJeH+mFX/g+6PxLQoiZLV8eOVCuUZCbkmo5+nf52qqhNALXjSpWMpoVtSi8VUhicPs9dsFz5Rgj2Wy2kt0i4TYhss0LwTkpWEauR4rMKKL2kr2KM21ZKi8H+xOhDFRZkj4=
  app: samyakkumar
  on: master