language: node_js
node_js:
- stable
cache:
  directories:
  - client/node_modules
  - server/node_modules
script:
- bash scripts/travis_test.sh
- bash scripts/travis_build.sh
true:
  branch: master
os:
- osx
